FP - Feat - Add Member
JoseScap/GymManagementApp pull request #21
Opened 2024-07-30 18:41 UTC by FranprzDev

2024-07-30 19:34 UTC, JoseScap requested changes

2024-07-30 19:34 UTC, JoseScap commented on src/modules/members/hooks/createMemberHooks.ts
> +    console.log("Test: ", fullName, dni, phoneNumber);
borrar console logs

2024-07-30 19:34 UTC, JoseScap commented on src/modules/members/hooks/createMemberHooks.ts
> +    }).finally(() => {
Este archivo solo debe tener la logica de todos los metodos, pero ningun efecto colateral (finally). Los callbacks los debe gestionar el elemento que llama a esta funcion.

Cual es el beneficio de esto, si yo necesito reutilizar esta funcion, el comportamiento base siempre lo puedo usar donde desee. Cuando uno genera efectos colaterales genera un acoplamiento a la situacion.

La solucion a esto seria mover el .finally al lugar en donde se llama esta funcion y que sea el componente o los componentes que usen este metodo quienes decidan cuales son las multiples acciones que se pueden realizar una vez finalizada esta accion.

2024-07-30 19:34 UTC, JoseScap commented on src/modules/members/hooks/createMemberHooks.ts
> +  const handleCreateMember = async () => {
los handlers solo deben estar en componentes, asi que la ubicacion de este metodo es correcto pero su nombre deberia ser solo createMember o cualquier otro, pero no debe empezar con handle

2024-07-30 19:34 UTC, JoseScap commented on src/modules/members/pages/CreateMemberPage.tsx
> +    handleCreateMember();
Aqui se debe implementar el finally

2024-07-30 19:34 UTC, JoseScap commented on src/modules/members/pages/CreateMemberPage.tsx
> +                onChange={(e) => { changeFullName(e.target.value) }} value={member?.fullName} required />
porque member no deberia existir? si en la firma del hook indicas que siempre existe el objeto member?

2024-07-30 19:34 UTC, JoseScap commented on src/modules/members/pages/CreateMemberPage.tsx
> +                onChange={(e) => { changeFullName(e.target.value) }} value={member?.fullName} required />
PD: No recuerdo si esto lo hice yo... pero en la firma no se indica que member sea nulo o undefined(opcional)

2024-07-30 22:48 UTC, FranprzDev commented on src/modules/members/pages/CreateMemberPage.tsx
> +                onChange={(e) => { changeFullName(e.target.value) }} value={member?.fullName} required />
Esto lo hice yo, pensé que era buena práctica agregar los '?' siempre; aunque no estoy seguro, le quito el '?'

2024-07-31 02:14 UTC, JoseScap approved these changes

2024-07-31 02:15 UTC, merged